version: '3'

services:

  build:
    image: tinygo/tinygo:latest
    container_name: envoy_wasm_ex_test_build
    working_dir: /build
    volumes:
      - ./:/build
    entrypoint: "/bin/sh -c 'tinygo build -o log_ext.wasm -scheduler=none -target=wasi main.go'"

  test:
    image: tinygo/tinygo:latest
    container_name: envoy_wasm_ex_test
    working_dir: /build
    volumes:
      - ./:/build
    entrypoint: "/bin/sh -c 'go test --tags=proxytest'"

